# Generated by Django 5.0.6 on 2024-07-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_carrinho',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
